input:
  image_dir: /folder/to/images

output:
  root_dir: /target/folder/
  image_folder: my_output
  image_subfix: .png
  
training:
  class_names: ["carton", "forklift", "pallet", "shutter door"]
  annotation_filename: colgate_ndc.names  # will be saved at output/root_dir
  

