# For label_tool_checker

checker:
  image_dir: /mnt/mydata/colgate_projects/label_tools_for_darknet/results/image_v2/loading_bay
  class_names: ["carton", "forklift", "pallet", "door", "covered_door"] 
