input_image_dir: /media/msasrock/Orange1TBWD/Colgate/media/colgate_201022_loadingbay

output_image_dir: /mnt/mydata/colgate_projects/label_tools_for_darknet/results/image_v2/loading_bay

object_classnames: ["carton", "forklift", "pallet", "door", "covered_door"] 

